### ISSUE TITLE
Update setup documentation to include database setup

### ISSUE THREAD

**Issue by alxrsngrtn** [jlevers/sunrise-strike-circles#15]
Either denote or link to docs to set up the postgresql server. 

Consequence: Without this, developers will fail at the `./manage.py migrate` or `.manage.py createsuperuser` steps.

**Comment by jlevers** [comment]
Related: we should remove my hardcoded database credentials from `common.py`, and replace them with credentials loaded from a `.env` file.

**Comment by jlevers** [comment]
Fixed by #24.
